cd pthat15;
crab -status short,color;
#crab -uploadLog;
cd ../pthat30;
crab -status short,color;
#crab -uploadLog;
cd ../pthat50;
crab -status short,color;
#crab -uploadLog;
cd ../pthat80;
crab -status short,color;
#crab -uploadLog;
cd ../pthat120;
crab -status short,color;
#crab -uploadLog;
cd ../pthat170;
crab -status short,color;
#crab -uploadLog;
cd ../pthat220;
crab -status short,color;
#crab -uploadLog;
cd ../pthat280;
crab -status short,color;
#crab -uploadLog;
cd ../pthat370;
crab -status short,color;
#crab -uploadLog;
cd ../pthat460;
crab -status short,color;
#crab -uploadLog;
cd ../pthat540;
crab -status short,color;
#crab -uploadLog;
cd ../;