cd pthat15;
crab -create;
crab -submit; 
crab -status short,color;
cd ../pthat30;
crab -create;
crab -submit; 
crab -status short,color;
cd ../pthat50;
crab -create;
crab -submit; 
crab -status short,color;
cd ../pthat80;
crab -create;
crab -submit; 
crab -status short,color;
cd ../pthat120;
crab -create;
crab -submit; 
crab -status short,color;
cd ../pthat170;
crab -create;
crab -submit; 
crab -status short,color;
cd ../pthat220;
crab -create;
crab -submit; 
crab -status short,color;
cd ../pthat280;
crab -create;
crab -submit; 
crab -status short,color;
cd ../pthat370;
crab -create;
crab -submit; 
crab -status short,color;
cd ../pthat460;
crab -create;
crab -submit; 
crab -status short,color;
cd ../pthat540;
crab -create;
crab -submit; 
crab -status short,color;
cd ../;